baseURL = "/"
languageCode = "en-us"
title = "SME Texaplex Virtual Chapter"
publishDir = "dist"
preserveTaxonomyNames = "true"

[sitemap]
  changefreq = "monthly"

[taxonomies]
  tag = "tags"

[params]
    [params.seo]
    description = "Official homepage for the SME Texaplex Virtual Chapter."
    keywords = ["engineering","manufacturing","sme","smetexaplex","education"]

    [params.social]
    description = "We work to energize, mobilize and engage the Texas engineering and manufacturing community."
    twitter_handle="@smevirtual"

    [params.external]
    meetup_group_url = "https://www.meetup.com/smevirtual"
    youtube_channel_url = "https://www.youtube.com/smevirtual"
    discussion_forum_url = "https://www.reddit.com/r/SMEVirtual"
    discord_chat_invite_url = "https://discord.gg/ufADa72"
    github_org_url = "https://github.com/smevirtual"
    linkedin_url = "https://www.linkedin.com/company/smevirtual"
    twitter_url = "https://twitter.com/smevirtual"
